hooks: precommit script updated.

diff --git a/.hooks/pre-commit b/.hooks/pre-commit
--- a/.hooks/pre-commit
+++ b/.hooks/pre-commit
@@ -1,20 +1,29 @@
 #!/usr/bin/env sh
 
+# Stop the process and return false to
+ctrl_c() {
+  echo Stoping checks...
+  false
+}
+
+# ctrl_c is the name of the signal ctrl_c function for SIGINT signal
+trap 'ctrl_c' SIGINT
+
 echo
 echo 🩺 Types checks...
 pnpm typecheck
 ERR=$?
 
 if [ $ERR -eq 0 ]; then
-  echo "Formated all staged files."
+  echo "Checking all staged files."
 else
-  echo "typechecks Failed."
+  echo "Typechecks Failed."
   echo "Fix type issues, add changes and try commit again."
-  false
+  exit 1
 fi
 
 echo
-echo 🛠️ Lint checks...
+echo  🛠️ Lint checks...
 pnpm lint-staged
 ERR=$?
 
@@ -23,5 +32,5 @@ if [ $ERR -eq 0 ]; then
 else
   echo "code formatting check Failed."
   echo "Run 'pnpm lint-staged', add changes and try commit again."
-  false
+  exit 1
 fi
